name: Issue Label helper

on:
  issues:
    types: [labeled]

jobs:
  label-helper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        if: github.event.label.name == 'mailing list question'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This tracker is for reporting issues in the C code, for questions about kamailio use sr-users@lists.kamailio.org mailing list.'
            })
