---
name: build
'on':
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest, ubuntu-24.04-arm]
    permissions:
      contents: read
    strategy:
      matrix:
        os:
        - centos-10
        - rhel-10
        - centos-9
        - rhel-9
        - centos-8
        - rhel-8
    steps:
    - uses: addnab/docker-run-action@v3
      with:
        image: alpine:latest
        run: uname -a